# base
ARG NODE_VERSION=12.13.1
FROM node:${NODE_VERSION}-alpine

LABEL maintainer="yaokun <yaokun@bwcxtech.com>"
USER root
RUN set -x \
    && apk update \
    && apk add --no-cache bash curl git tzdata autoconf automake gcc \
    && npm install -g cnpm@6.0.0 --registry=https://registry.npm.taobao.org
