# base
ARG NODE_VERSION=12.13.1
FROM node:${NODE_VERSION}-alpine

LABEL maintainer="yaokun@bwcxtech.com"
USER root
RUN set -x \
    && apt update \
    && apt install curl -y \
    && curl -OL https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz \
    && tar -zxf docker-latest.tgz \
    && cp docker/docker /usr/local/bin/ \
    && rm -rf docker docker-latest.tgz

RUN npm install -g cnpm --registry=https://registry.npm.taobao.org \
    # 配置npm私有仓库
    && npm config set registry http://192.168.1.200:8081/nexus/repository/npm-group/ \
    && cnpm config set registry http://192.168.1.200:8081/nexus/repository/npm-group/ \
    && git config --global user.email "jenkins@example.com" \
    && git config --global user.name "jenkins" \
    && git config --global credential.helper store
