# base
ARG NODE_VERSION=14.19.3-slim
FROM node:${NODE_VERSION}

ENV TZ "Asia/Shanghai"

LABEL maintainer="yaokun <yaokun@bwcxtech.com>"
USER root

RUN npm config set registry https://registry.npmmirror.com \
    && npm install -g cnpm@6.2.0 --registry=https://registry.npmmirror.com
